### ISSUE TITLE
Login failed. Please check your credentials

### ISSUE THREAD

**Issue by fsmeets84** [Dr-Blank/Vaani#15]
Audiobookshelf:

- Installed ABS on a Synology NAS via Docker
- Setup a reverse proxy to my own domain

After installing Vaani app I filled in the server url, username and password. However I get the error message: Login failed. Please check your credentials

Already tried to change the password to rule out special characters were causing the issue. But it didn't work as well.

**Comment by Dr-Blank** [comment]
ty for reporting

could you please check:
1. Can you login through web app? (I could not when there was whitespace at the end of username/password)
2. What is your server version? (Vaani is tested with latest version (2.12.3), most likely if it is old version it might not work)

If removing spaces at end and upgrading does not work, I might not have other way to reproduce this other than asking for characters that might be causing this issue, which could be a security risk. And if your username and password is made up of only letters, (e.g. foo & bar) and you are getting this error, I do not know how to help you, i will have to figure out a way to get logs from you.

**Comment by Dr-Blank** [comment]
> I noticed on Reddit I'm not the only one who has this problem. I can make a copy of my setup of Audiobookshelf and check if I have the same issue. If the error still appears, I can give you access to my duplicate setup.

that would be great if i can reproduce the error somehow. I did see on reddit many reports of this issue, but without reproducibility i can not work on it unfortunately.

**Comment by fsmeets84** [comment]
I have setup a second Docker environment for Audiobookshelf with reverse proxy.
When I enter the url, username and password I get the same error message. I can send you all the necessary information to use this server to login.

**Comment by fsmeets84** [comment]
I have send all the information via Reddit

**Comment by Dr-Blank** [comment]
closing as recent build fixes this
