### ISSUE TITLE
Error after ABS crashed

### ISSUE THREAD

**Issue by Woocaa** [Dr-Blank/Vaani#16]
Hi! 

Love the app! Keep up the good work! 

My ABS crashed recently, now when I login the main page just shows this: Error:type 'Null' is not a subtype of type 'List<dynamic>' in type cast. App works and I can play audiobooks but I have to search for the book. I have tried deleting my account and re-login,, the error remains.

**Comment by Dr-Blank** [comment]
I would suggest to delete app storage and cache. if the error persists, you might have to wait until i implement some sort of logs reporting beck here because without logs I would not be able to help you sorry.

**Comment by Woocaa** [comment]
That did the trick! Appreciate it! Looking forward to future updates of your app 😁 Thanks!
-------- Original message --------From: "Dr.Blank" ***@***.***> Date: 2024-08-28  10:51 a.m.  (GMT-05:00) To: Dr-Blank/Vaani ***@***.***> Cc: Woocaa ***@***.***>, Author ***@***.***> Subject: Re: [Dr-Blank/Vaani] Error after ABS crashed (Issue #16) 
I would suggest to delete app storage and cache. if the error persists, you might have to wait until i implement some sort of logs reporting beck here because without logs I would not be able to help you sorry.
