### ISSUE TITLE
http support

### ISSUE THREAD

**Issue by sujansujan** [Dr-Blank/Vaani#17]
I'm not able to use my http url as a server as there is only support for https.
It being http isn't a problem as i use audiobookshelf with tailscale.

**Comment by Dr-Blank** [comment]
What happens when you enter your address starting with http:// ? It should work despite the label showing https. If not I'll have to reproduce

**Comment by sujansujan** [comment]
sorry. it didn't work the last time, now it is working. thank you for making the app. main audiobookshelf app is abit clunky.

**Comment by maxmustermann1234** [comment]
I have the same Problem. My Server ist only reachable via http. https://youtu.be/DjkxB4OZvcI?si=K0xz0KCq7t1nllb0

**Comment by Dr-Blank** [comment]
@maxmustermann1234 by default https is used, to override you need to manually type `http://<your_server>`, maybe in future I will add some retries with http, for now this workaround should work

**Comment by maxmustermann1234** [comment]
Thank you! I tried that, and it worked. Thank you. Unfortunately, the login failed. I should check the credentials, but they are correct. Should I send you an account via private message to reproduce the issue?
