### ISSUE TITLE
Unable to play

### ISSUE THREAD

**Issue by maxmustermann1234** [Dr-Blank/Vaani#44]
I'm unable to Play Audiobooks. With the official Apps IT IS working without problems. I am pressing in Play and nothing ist happening. 
![Screenshot_20241003-000230](https://github.com/user-attachments/assets/c25fb6bc-8305-4f94-8f14-7b1ade40c0f4)

I'm using the most-up-to-date Version of Audiobookshelf and vaani

**Comment by Dr-Blank** [comment]
Hi, is there a way you can create a test user with access to only the item causing issue? If so you can send me the details on my profile's email so I can reproduce this and fix.

If that is not possible please wait till #24 is completed because until that I would not know what is going on.

**Comment by sujansujan** [comment]
thanks man, it has worked now.
